### ISSUE TITLE
Jobs cannot be loaded if the project is inside a directory with a space in its name

### ISSUE THREAD

**Issue by Kevenvz** [timmolter/dropwizard-sundial#6]
So I constantly ran into this error:

```
INFO  [2016-05-18 13:20:15,003] org.quartz.classloading.CascadingClassLoadHelper: Package: 'nl.glu.voteapp.jobs' becomes Resource: 'file:/E:/Development/Studenten%20App/glu-app-backend/target/classes/nl/glu/voteapp/jobs'
ERROR [2016-05-18 13:20:15,006] org.knowm.sundial.ee.SundialInitializerListener: Sundial Scheduler failed to initialize: 
! java.lang.NullPointerException: null
```

Then I removed the space in the directory name and it worked. I guess the fix is to not encode the directory path so that it doesn't add the %20 but instead uses a normal space.

**Comment by timmolter** [comment]
I've seen this before, and I think was fixed somewhere else in the code. I'll look into it.

**Comment by timmolter** [comment]
OK, fix pushed. please try snapshot jar.

**Comment by daghendrik** [comment]
I am still getting this error using the latest version (1.3.1). I am on Windows and my username contains spaces. My project folder resides in "C:\Users\User Name With Spaces\Documents". 

I tried moving the project folder to root a.k.a. " C:\ " and the problem went away.

If you can take another look at this issue, I'll be happy to test and verify a fix.

Thanks for a great project!

**Comment by timmolter** [comment]
Done. Here's what was fixed in [CascadingClassLoadHelper.java](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html):

Root cause: [URLDecoder.decode(resource.getPath(), "UTF-8")](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) doesn't properly handle Windows drive-letter paths (e.g. /C:/Users/... — the leading / confuses [new File()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)), so the [File](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) object pointed to a non-existent path, and [directory.list()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) returned null, causing the NPE.

Fix 1 — Use [new File(resource.toURI()).getAbsolutePath()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) for filesystem resources. [URL.toURI()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) + new File(URI) is the correct Java idiom — it handles %20 decoding, Windows drive letters, and all edge cases. Falls back to [URLDecoder](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) if [toURI()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) throws.

Will be released in near future.
